name: Manage Wishlist Actions

on:
  repository_dispatch:
    types: [wishlist-approved]
  workflow_dispatch:
    inputs:
      wishlist_id:
        description: 'Wishlist ID'
        required: true
        type: number

jobs:
  manage-wishlist:
    runs-on: ubuntu-latest
    steps:
      - uses: oss-wishlist/manage-wishlist-actions@v1.1.2
        with:
          github-token: ${{ secrets.WISHLIST_BOT_TOKEN }}
          database-url: ${{ secrets.DATABASE_URL }}
          wishlist-id: ${{ github.event.client_payload.wishlist_id || github.event.inputs.wishlist_id }}

